Ft user send mail
neelxie/epic-mail pull request #8
Opened 2019-03-15 08:18 UTC by neelxie

[#164605537] Send email to individuals
[#164605796] Save draft or delete draft
#### A user who wants to send a message
#### A user' compose an email, and either send it or save it
#### You can check it out [here](https://neelxie.github.io/epic-mail/UI/compose.html)
@bekeplar @jennizalwango @alexxsanya @Wabuluka @kyakusahmed

2019-03-15 08:58 UTC, Emmanuelaaron commented
So far so good,
I love the responsiveness of your templates

2019-03-22 15:53 UTC, byarustev requested changes

2019-03-22 15:53 UTC, byarustev commented on UI/assets/css/styles.css
> +    /* display: flex; */
remove this comment

2019-03-22 15:53 UTC, byarustev commented on UI/assets/css/form.css
> +    /* background-color: white; */
remove this comment

2019-03-22 17:02 UTC, bekeplar commented
Kill the commented code from your code

2019-03-23 06:09 UTC, neelxie commented
Thanks, all fixed now.


On 3/22/19, Bekalaze Joseph <notifications@github.com> wrote:
> Kill the commented code from your code
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/neelxie/epic-mail/pull/8#issuecomment-475699944

2019-03-25 14:27 UTC, closed without merging